version: 2.1

jobs:
  build_deploy_counting_container_unstable:
    machine: true  # docker enabled
    steps:
      - checkout  # get code
      - run: docker build -t $DOCKER_HUB_USERNAME/loculator:unstable counting-app
      - run: docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
      - run: docker push $DOCKER_HUB_USERNAME/loculator

  build_deploy_counting_container_stable:  # same as above, but with stable tags
    machine: true
    steps:
      - checkout
      - run: docker build -t $DOCKER_HUB_USERNAME/loculator:stable -t $DOCKER_HUB_USERNAME/loculator:latest counting-app
      - run: docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
      - run: docker push $DOCKER_HUB_USERNAME/loculator

workflows:
  version: 2
  standard:
    jobs:
      - build_deploy_counting_container_unstable:
          filters:
            branches:
              ignore: master

  master_workflow:
    jobs:
      - build_deploy_counting_container_stable:
          filters:
            branches:
              only: master
